dist: trusty

addons:
  sonarcloud:
    organization: "sanogotech"
    token:
      secure: "5fac9fecb4d26f94c40ac890d02357ab039ed104" # encrypted value of your token

install: composer install --prefer-dist

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - vendor/bin/phpunit  --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
