dist: trusty

addons:
  sonarcloud:
    organization: "sanogotech"
    token:
      secure: "6fb23963c7d0a6c8f22df225d36a45a3f9c6d6ae" # encrypted value of your token

install: composer update

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner